GET http://localhost:5001/api/user/points
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MTE5OTNiZi01ZjQ2LTQzMGQtOTkzMi01NzUwYzc2NDdiZDEiLCJqdGkiOiI5YWI5NGU4YS02ZTExLTRmMjUtOTUwZi0xZTZjZjI1YjFjMGIiLCJnaXZlbl9uYW1lIjoiV2lrdG9yIiwiZmFtaWx5X25hbWUiOiJLcnp5Y3prb3dza2kiLCJhdWQiOiJRdWl6ekFwcCIsImV4cCI6MTczMzI0NTM2OSwiaXNzIjoiUXVpenpBcHAifQ.eHuT8jwFDncr-eEiY55b2B3FSVz1DRbmhpI7cEaie64