POST http://localhost:5001/api/question/answer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZTViZTg5OS05N2IwLTRhYjEtODgxZi0yZDg1YmEwZTUzYjUiLCJqdGkiOiI0ZmU3NDY5Yy0wNTQ1LTQ2MDYtOTAwNy05ZDEyNTA2MjkxNjgiLCJnaXZlbl9uYW1lIjoiV2lrdG9yMiIsImZhbWlseV9uYW1lIjoiS3J6eWN6a293c2tpMiIsImF1ZCI6IlF1aXp6QXBwIiwiZXhwIjoxNzMzMjQzOTA0LCJpc3MiOiJRdWl6ekFwcCJ9.oL5W-qmZduOtDC4bwaey0QNUV_boWoGm319AVPbqQfY

{
  "QuestionId": "E39259DF-13E0-4FEA-97FB-03D2480AD301",
  "Answer":"Long Term Support"
}
