GET http://localhost:5001/api/question
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MTE5OTNiZi01ZjQ2LTQzMGQtOTkzMi01NzUwYzc2NDdiZDEiLCJqdGkiOiI0ZmFjMjFlNi0zNWQyLTRlZTYtOThmYy02MzVjNGZlN2E1NGEiLCJnaXZlbl9uYW1lIjoiV2lrdG9yIiwiZmFtaWx5X25hbWUiOiJLcnp5Y3prb3dza2kiLCJhdWQiOiJRdWl6ekFwcCIsImV4cCI6MTczMzIxODk5MywiaXNzIjoiUXVpenpBcHAifQ.YXZeu5lSY4mb2Dlpyd2cx9bpA4XEjgUHjbZ7xkUZb_A

{
  "take":3
}